# This docker compose is for streamoo application
name: "streamoo"
version: "v0.1"
services:
  mongodb:
    image: mongo
    ports:
      - ${MONGODBPORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOPASS}
    volumes:
      - ./mongo_data:/data/db
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGOEXPPORT}:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGOUSER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGOPASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGOUSER}:${MONGOPASS}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

  backend:
    build: backend/.
    container_name: backend
    ports:
      - ${BACKENDPORT}:3000           #The first port number here is our host port where we can see it and another is docker virtual port we are port binding here!
    depends_on:
      - mongodb
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build: frontend/.
    container_name: frontend
    ports:
      - ${FRONTENDPORT}:5173
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app/frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
